NumPy website
https://numpy.org/doc/stable/

In [111]:
summ=0
for num in range(1,9999999):
    summ +=num
summ

49999985000001

In [112]:
summ=0
for num in range(1,9999999):
    summ +=num**2
summ

333333183333354999999

In [113]:
summ=[]
for num in range(1, 1000000):
    summ.append(num**8)
summ


[1,
 256,
 6561,
 65536,
 390625,
 1679616,
 5764801,
 16777216,
 43046721,
 100000000,
 214358881,
 429981696,
 815730721,
 1475789056,
 2562890625,
 4294967296,
 6975757441,
 11019960576,
 16983563041,
 25600000000,
 37822859361,
 54875873536,
 78310985281,
 110075314176,
 152587890625,
 208827064576,
 282429536481,
 377801998336,
 500246412961,
 656100000000,
 852891037441,
 1099511627776,
 1406408618241,
 1785793904896,
 2251875390625,
 2821109907456,
 3512479453921,
 4347792138496,
 5352009260481,
 6553600000000,
 7984925229121,
 9682651996416,
 11688200277601,
 14048223625216,
 16815125390625,
 20047612231936,
 23811286661761,
 28179280429056,
 33232930569601,
 39062500000000,
 45767944570401,
 53459728531456,
 62259690411361,
 72301961339136,
 83733937890625,
 96717311574016,
 111429157112001,
 128063081718016,
 146830437604321,
 167961600000000,
 191707312997281,
 218340105584896,
 248155780267521,
 281474976710656,
 318644812890625,
 360040606269696,
 406067677556641,
 4571632

In [114]:
import numpy as np


In [115]:
array = np.arange(1,1000000,dtype=np.int64)**8 # insted of built-in data structer we use numpy because there use broadcasting and vectorization mothod 
array                                            # 1 & 1000000 are treat as vector

array([                   1,                  256,                 6561,
       ..., -5454243775671954527, -1594273250544254720,
        2632184273707445761], dtype=int64)

# ceration of arrays

In [116]:
# convert a list into a array
arr=np.array([1,2,3,4,5,6]) # here the list convert into a array by np.array()
arr

array([1, 2, 3, 4, 5, 6])

In [117]:
arr**2 # c=because of broadcasting and vectorization we can easily squred this array without looping

array([ 1,  4,  9, 16, 25, 36])

In [118]:
# convert a tuple into a array
arr=np.array((1,2,3,4,5,6)) # here the tuple convert into a array by np.array()
arr

array([1, 2, 3, 4, 5, 6])

In [119]:
arr.dtype #return data type here dtype('int32')

dtype('int32')

In [120]:
arr1=np.array((1,2,3,4,5,6), dtype=np.int32) #converting data type int32 to int64
arr1.dtype
arr1.itemsize

4

In [121]:
arr11=np.array((1,2,3,4,5,6), dtype=np.float64) #converting data type int32 to int64
arr1
arr1.dtype
arr11.itemsize

8

In [122]:
arr1.ndim # return dimention

1

In [123]:
arr1.size # return the number of element inside array size

6

In [124]:
# convert a tuple into a array
arr=np.array((1,2,3,4,5,6)) # here the tuple convert into a array by np.array()
arr

array([1, 2, 3, 4, 5, 6])

In [125]:
arr2=np.arange(20,2000,2,dtype=np.int64)
arr2

array([  20,   22,   24,   26,   28,   30,   32,   34,   36,   38,   40,
         42,   44,   46,   48,   50,   52,   54,   56,   58,   60,   62,
         64,   66,   68,   70,   72,   74,   76,   78,   80,   82,   84,
         86,   88,   90,   92,   94,   96,   98,  100,  102,  104,  106,
        108,  110,  112,  114,  116,  118,  120,  122,  124,  126,  128,
        130,  132,  134,  136,  138,  140,  142,  144,  146,  148,  150,
        152,  154,  156,  158,  160,  162,  164,  166,  168,  170,  172,
        174,  176,  178,  180,  182,  184,  186,  188,  190,  192,  194,
        196,  198,  200,  202,  204,  206,  208,  210,  212,  214,  216,
        218,  220,  222,  224,  226,  228,  230,  232,  234,  236,  238,
        240,  242,  244,  246,  248,  250,  252,  254,  256,  258,  260,
        262,  264,  266,  268,  270,  272,  274,  276,  278,  280,  282,
        284,  286,  288,  290,  292,  294,  296,  298,  300,  302,  304,
        306,  308,  310,  312,  314,  316,  318,  3

In [126]:
arr2.shape # return number of values
arr2.size # return number of values


990

In [127]:
# create expected elements 
# syntex: linespace(start, stop, expected elements)
arr3=np.linspace(20, 2000, 20000) # sequentiully return expected values 
arr3

array([  20.        ,   20.09900495,   20.1980099 , ..., 1999.8019901 ,
       1999.90099505, 2000.        ])

In [128]:
arr3.shape

(20000,)

In [129]:
np.random.random(2000) # create random number

array([0.47184708, 0.95785039, 0.36944329, ..., 0.66986012, 0.12980822,
       0.83792737])

In [130]:
np.random.randint(20, 2000) # return a single random int number between 20-2000

317

In [131]:
arr4=np.random.randn(3,2) # return random values according to dimention
arr4

array([[ 0.47554984,  1.35577792],
       [-0.23825405,  1.19926875],
       [ 0.69549117,  0.01111474]])

In [132]:
arr4.ndim # return dimention

2

In [133]:
arr5=np.random.randn(3,2,3) # return 3 dimentional random values according to dimention
arr5

array([[[-1.53340675,  1.98281247,  0.37986645],
        [-0.12189255, -0.89464054, -0.38489029]],

       [[ 0.5892365 , -0.91349099, -0.48053065],
        [ 1.27712443, -0.19561718, -0.22901753]],

       [[ 0.52154098,  1.38839965,  0.0350167 ],
        [ 0.02286956,  0.48812324, -0.46787753]]])

In [134]:
arr5.ndim
arr.itemsize # return index size, here each number consume 8 byte memory

4

# instant array generation

In [135]:
# # matrix creating
m=np.zeros([2,2]) # row a7 col size alway remain into list / touple 
m

array([[0., 0.],
       [0., 0.]])

In [136]:
m.ndim

2

In [137]:
m1=np.ones((3,3)) # generating matrix
m1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [138]:
m2=np.empty([3,2]) #generating matrix
m2

array([[0.47554984, 1.35577792],
       [0.23825405, 1.19926875],
       [0.69549117, 0.01111474]])

In [139]:
m4=np.eye(3,3) # generating identity matrix, here 1 lies diagnally
m4

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [140]:
m4=np.eye(3,3,k=1) # here indexing shift 1 step right size 
m4

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [141]:
m5=np.eye(3,3,k=-1) # here indexing shift 1 step left size 
m5

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [142]:
m6=np.full([3,3], 5) # here we can fill matrix values in customize way
m6

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

# Array Dtypes

In [143]:
np.arange(1,20) # arange() generate int elements (by defolt)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [144]:
np.arange(1,20, dtype=np.float64)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19.])

In [145]:
np.arange(1,20, dtype=np.complex64) # generating complex number

array([ 1.+0.j,  2.+0.j,  3.+0.j,  4.+0.j,  5.+0.j,  6.+0.j,  7.+0.j,
        8.+0.j,  9.+0.j, 10.+0.j, 11.+0.j, 12.+0.j, 13.+0.j, 14.+0.j,
       15.+0.j, 16.+0.j, 17.+0.j, 18.+0.j, 19.+0.j], dtype=complex64)

In [146]:
np.array([True, False, True, True, False], dtype=np.bool8) #generating boolian data

array([ True, False,  True,  True, False])

In [147]:
#generating boolian data
np.array([True, False, True, True, 1,0,22], dtype=np.bool8) #here zero treat as False and other one 

array([ True, False,  True,  True,  True, False,  True])

In [148]:
np.array(['Apple','mango','orange'], dtype=np.string_) #generating string data type

array([b'Apple', b'mango', b'orange'], dtype='|S6')

# Slicing

In [149]:
# generating customize matrix
arr6=np.array(

    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ]
)

In [150]:
arr6 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [151]:
arr6[0] # return first row

array([1, 2, 3])

In [152]:
arr6[0][1] # return first row's 2nd value
arr6[0,1] #same 

2

In [153]:
#    rows    column
arr6[0:2:1,  1:3:1] # its will be increase upto n dimentions

array([[2, 3],
       [5, 6]])

In [154]:
# 3 dimention
d=np.random.randn(3,3,3)
d

array([[[-0.67598815,  0.10560149, -0.7670459 ],
        [ 1.99678953,  1.19921601,  0.36223551],
        [-0.80141587,  0.13401338, -1.74147418]],

       [[-1.63193679, -0.05387619, -0.28317198],
        [ 0.4638132 , -0.3090472 ,  0.44071454],
        [ 0.31085216, -0.25548453, -0.14873047]],

       [[ 2.0484315 , -3.17909804,  0.02834734],
        [-0.37456749,  0.00612567,  0.6771577 ],
        [-2.18872899,  0.35452377, -0.80192408]]])

In [155]:
d[0] # return first row's values

array([[-0.67598815,  0.10560149, -0.7670459 ],
       [ 1.99678953,  1.19921601,  0.36223551],
       [-0.80141587,  0.13401338, -1.74147418]])

In [156]:
d[0][1] #return first roew's 2nd column's values

array([1.99678953, 1.19921601, 0.36223551])

In [157]:
d[0][1][1] #return 1st row's 2nd column's 2nd index values

1.1992160093249304

#  Filter

In [158]:
ar=np.arange(5,25)
ar

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24])

In [159]:
ar>10

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [160]:
ar[ar>10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [161]:
ar[(ar>10) & (ar<20)] # and operation

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [162]:
ar[(ar<5) | (ar>20)] # or operation

array([21, 22, 23, 24])

In [163]:
ar[~(ar>10)] # not operation

array([ 5,  6,  7,  8,  9, 10])

# Scaler

In [164]:
# generating customize matrix
arr7=np.array(

    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ]
)

In [165]:
arr7

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [166]:
arr7[arr7>4]

array([5, 6, 7, 8, 9])

In [167]:
#adding
arr7+4
np.add(arr7,4) # both are similar

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [168]:
#sqired
arr7**2
np.power(arr7,2) # both are similar

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]], dtype=int32)

In [169]:
# subtracting
arr7-2 
np.subtract(arr7, 2) # similar

array([[-1,  0,  1],
       [ 2,  3,  4],
       [ 5,  6,  7]])

In [170]:
# multiply
arr7*3 
np.multiply(arr7,3) # similar

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

In [171]:
# division
arr7/4
np.divide(arr7,4)

array([[0.25, 0.5 , 0.75],
       [1.  , 1.25, 1.5 ],
       [1.75, 2.  , 2.25]])

In [172]:

#reminder
arr7%3, np.mod(arr7,3)  # both are similar

(array([[1, 2, 0],
        [1, 2, 0],
        [1, 2, 0]], dtype=int32),
 array([[1, 2, 0],
        [1, 2, 0],
        [1, 2, 0]], dtype=int32))

# matrix and vector operation

In [173]:
x=np.eye(3,3)
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [174]:
y=np.eye(3,3,k=1)
y

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [175]:
# matrix addition
x+y

array([[1., 1., 0.],
       [0., 1., 1.],
       [0., 0., 1.]])

In [176]:
a=np.array(

    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ]
)

In [177]:
b=np.array(

    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ]
)

In [178]:
# addition
a+b

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [179]:
# multiplication
a*b

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [180]:
#power
a**b

array([[        1,         4,        27],
       [      256,      3125,     46656],
       [   823543,  16777216, 387420489]])

In [181]:
# subtract
a-b

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [182]:
# division
a/b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [183]:
# matrix multiplication
a@b
np.matmul(a,b) # similar

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

# statistics


In [184]:
# adding matrix all values
a.sum()

45

In [185]:
# row wise sum
a.sum(axis=1)

array([ 6, 15, 24])

In [186]:
# column wise sum
a.sum(axis=0)

array([12, 15, 18])

In [187]:
# mean of all values of matrix a
a.mean()

5.0

In [188]:
a.mean(axis=1) # row wise mean

array([2., 5., 8.])

In [189]:
a.mean(axis=0) # column wise mean

array([4., 5., 6.])

In [190]:
# standard deviasion
a.std()

2.581988897471611

In [191]:
a.std(axis=1) # row wise std

array([0.81649658, 0.81649658, 0.81649658])

In [192]:
a.std(axis=0) # column wise std

array([2.44948974, 2.44948974, 2.44948974])

In [193]:
# varience
a.var() 

6.666666666666667

In [194]:
a.var(axis=1) # row wise varience

array([0.66666667, 0.66666667, 0.66666667])

In [195]:
a.var(axis=0) # column wise variance

array([6., 6., 6.])

In [196]:
# return max value
a.max()

9

In [197]:
# return min value
a.min()

1

In [198]:
# return value diagonaly
a.diagonal()

array([1, 5, 9])

In [199]:
# copy this matrix
p=a.copy()
p

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [200]:
# transpose this matrix
a.transpose()
a.T # similar

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [201]:
# return the index number of minimum values
a.argmin()

0

In [202]:
# return the index number of maximum values
a.argmax()

8

In [203]:
# return median
np.median(a)

5.0

In [204]:
# return median row wise
np.median(a,axis=1)

array([2., 5., 8.])

In [205]:
# return median column wise
np.median(a,axis=0)

array([4., 5., 6.])

In [206]:
# return covariance of 1st row & column
np.cov(a[0],b[0])

array([[1., 1.],
       [1., 1.]])

In [207]:
#Covariance calculation
  # x  y
# x 1  1
# y 1  1

In [208]:
np.cov([3,4,5,6],[3,5,7,4])

array([[1.66666667, 0.83333333],
       [0.83333333, 2.91666667]])

# Shaping

In [209]:
arra=np.arange(1,21)
arra

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [210]:
arra.reshape(10,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20]])

In [211]:
arra.reshape(5,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [212]:
n_arr=arra.reshape(5,4)
n_arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [213]:
#return previous one 
n_arr.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [214]:
n_arr.reshape(20,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20]])

In [ ]:
# 3 dimentional 
p.reshape(2,5,2)

# Save NumPy data

In [ ]:
np.save('array',n_arr) # Save an array to a binary file in NumPy

In [ ]:
np.savetxt('array',n_arr) #Save an array to a text file.

# loading data from Numpy file

In [ ]:
np.load('array.npy') # Load arrays or pickled objects from .npy, .npz or pickled files.

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [ ]:
np.loadtxt('array') #Load data from a text file.



array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.],
       [13., 14., 15., 16.],
       [17., 18., 19., 20.]])